// Generated by https://quicktype.io

export interface ICredential {
	status: number;
	data: IData;
	info: string;
}

export interface IData {
	id: string;
	login_with: string;
	name: string;
	username: string;
	image: string;
	email: string;
	gender: string;
	login_token: string;
	type: string;
	expirated: string;
	teks_expirated: string;
	is_expirated: boolean;
	user_age_18_plus: string;
	token_plus: string;
	pwd: string;
	hp: string;
}
export interface ISearch {
	id: string;
	link: string;
	title: string;
	image: string;
	shoot: string;
	category: string;
	date: string;
	time: string;
	tipe: string;
	hits: string;
	title_eps: string;
	jumlah_favorit: string;
}
export interface IEpisode {
	episode_id: string;
	episode_number: string;
	episode_name: string;
}


export interface IDownloadLink {
	status:string;
	'360p':string;
	'480p':string;
	'720p':string;
	'360p_size':string;
	'480p_size':string;
	'720p_size':string;
  }